uint32 pin
# PWM frequency in Hz (0=off, 0.1-10000).
uint32 frequency
# PWM duty cycle in % (0-100).
float32 duty
# Optional output pin modes, separated by pipe symbol.
string mode
---
# On failure returns false
string error